export enum AuditAction {
  SITUATION_CREATED = 'SITUATION_CREATED',
  SITUATION_UPDATED = 'SITUATION_UPDATED',
  SITUATION_STATUS_CHANGED = 'SITUATION_STATUS_CHANGED',
  AI_ANALYSIS_COMPLETED = 'AI_ANALYSIS_COMPLETED',
  AI_REANALYZED = 'AI_REANALYZED',
  AI_ANALYSIS_FAILED = 'AI_ANALYSIS_FAILED',
  USER_CREATED = 'USER_CREATED',
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
  USER_ACTIVATED = 'USER_ACTIVATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
}

export enum AuditResourceType {
  SITUATION = 'situation',
  USER = 'user',
  AI_ANALYSIS = 'ai_analysis',
}
